### PR TITLE
Remove arrow function

### PR DESCRIPTION
**Pull request by conartist6**
Avoid forcing webpack users of the package to do custom transpilation of this dependency.

### CODE REVIEW

**Comment by SamVerschueren** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

**Comment by conartist6** [comment]
OK if a single several character change to a micro-library which clearly has no unique applicability to node is too difficult for you, I'll just fork it. Good day.

**Comment by conartist6** [comment]
I'm sorry, I don't mean to be an asshole. Your webpack plugin is lovely. I just happen to have real problems at the moment.

**Comment by conartist6** [comment]
OK, I've got my version ready to go. I realize I had neglected to change the lint configuration. https://github.com/conartist6/clone-regexp-compatible

I'll wait a day before I publish it because obviously once I do I can't take it back, but I really don't see how it is not the most logical course of action for a person in my position.

**Pull request closed without merging**
